contact_links:
  - name: ğŸ’¬ Bug reports and feature requests for Misskey itself
    url: https://github.com/misskey-dev/misskey/issues
    about: Misskeyæœ¬ä½“ã«é–¢ã™ã‚‹ãƒã‚°å ±å‘Šãƒ»æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆã¯ã“ã¡ã‚‰ã‹ã‚‰
  - name: ğŸ–¥ Bug reports and feature requests for Server List API
    url: https://github.com/joinmisskey/api/issues
    about: ã‚µãƒ¼ãƒãƒ¼ä¸€è¦§ãƒšãƒ¼ã‚¸ã§ä½¿ç”¨ã—ã¦ã„ã‚‹ã€Œã‚µãƒ¼ãƒãƒ¼ä¸€è¦§APIã€ã«é–¢ã™ã‚‹ãƒã‚°å ±å‘Šãƒ»æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆã¯ã“ã¡ã‚‰ã‹ã‚‰
