contact_links:
  - name: ğŸ’¬ Bug reports and feature requests for Misskey itself
    url: https://github.com/misskey-dev/misskey/issues
    about: Misskeyæœ¬ä½“ã«é–¢ã™ã‚‹ãƒã‚°å ±å‘Šãƒ»æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆã¯ã“ã¡ã‚‰ã‹ã‚‰
